### ISSUE TITLE
New name required

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pymetrius#1]
urgently! 😄

**Comment by MischaPanch** [comment]
> urgently! 😄

@mdbenito what would you propose? In the end it is a generic template for a python library

**Comment by mdbenito** [comment]
acronyms, random names, funny cartoon name, anything but boring_name_with_underscores 
* YetAnotherTemplate
* YAT
* NotInventedHere
* NIH
* PLyT
* PyLyTe
* PLiTe
* Obelix
* Coiner
* Clone

**Comment by MischaPanch** [comment]
Renamed it to pymetrius, based on [Demetrius of Phalerum](https://en.wikipedia.org/wiki/Demetrius_of_Phalerum), one of the founders of the Alexandria library. I know, not terribly creative ^^
