### ISSUE TITLE
Build dist with poetry

### ISSUE THREAD

**Issue by carlocagnetta** [appliedAI-Initiative/pymetrius#14]
https://github.com/appliedAI-Initiative/pymetrius/blob/5523ddbd97420d6e27cc7333bdc4972f1ca32ca0/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/publish.yaml#L26-L29

**Comment by carlocagnetta** [comment]
@MischaPanch I did not really understand this.
Also, we are missing the step to publish github pages I guess.

**Comment by MischaPanch** [comment]
This is for publishing an artifact to pypi. Previously it was done by setup tools, now it has to be done by poetry. I'm sure there's a bunch of explanations online how to do that, should be in official poetry docs

**Comment by MischaPanch** [comment]
Done in 5fe7a71d54
